# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='message.proto',
    package='',
    syntax='proto3',
    serialized_options=None,
    serialized_pb=_b(
        '\n\rmessage.proto\"(\n\x07Request\x12\r\n\x05tasks\x18\x01 \x03(\t\x12\x0e\n\x06smiles\x18\x02 \x03(\t\"\x18\n\tListValue\x12\x0b\n\x03val\x18\x01 \x03(\x02\"x\n\tTaskScore\x12-\n\ntask_score\x18\x01 \x03(\x0b\x32\x19.TaskScore.TaskScoreEntry\x1a<\n\x0eTaskScoreEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x19\n\x05value\x18\x02 \x01(\x0b\x32\n.ListValue:\x02\x38\x01\"v\n\x08Response\x12\x0b\n\x03msg\x18\x01 \x01(\t\x12#\n\x05score\x18\x02 \x03(\x0b\x32\x14.Response.ScoreEntry\x1a\x38\n\nScoreEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x19\n\x05value\x18\x02 \x01(\x0b\x32\n.TaskScore:\x02\x38\x01\x32\x38\n\x0eMolePropServer\x12&\n\rget_mole_prop\x12\x08.Request\x1a\t.Response\"\x00\x62\x06proto3')
)

_REQUEST = _descriptor.Descriptor(
    name='Request',
    full_name='Request',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='tasks', full_name='Request.tasks', index=0,
            number=1, type=9, cpp_type=9, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='smiles', full_name='Request.smiles', index=1,
            number=2, type=9, cpp_type=9, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=17,
    serialized_end=57,
)

_LISTVALUE = _descriptor.Descriptor(
    name='ListValue',
    full_name='ListValue',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='val', full_name='ListValue.val', index=0,
            number=1, type=2, cpp_type=6, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=59,
    serialized_end=83,
)

_TASKSCORE_TASKSCOREENTRY = _descriptor.Descriptor(
    name='TaskScoreEntry',
    full_name='TaskScore.TaskScoreEntry',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='key', full_name='TaskScore.TaskScoreEntry.key', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='value', full_name='TaskScore.TaskScoreEntry.value', index=1,
            number=2, type=11, cpp_type=10, label=1,
            has_default_value=False, default_value=None,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=_b('8\001'),
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=145,
    serialized_end=205,
)

_TASKSCORE = _descriptor.Descriptor(
    name='TaskScore',
    full_name='TaskScore',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='task_score', full_name='TaskScore.task_score', index=0,
            number=1, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[_TASKSCORE_TASKSCOREENTRY, ],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=85,
    serialized_end=205,
)

_RESPONSE_SCOREENTRY = _descriptor.Descriptor(
    name='ScoreEntry',
    full_name='Response.ScoreEntry',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='key', full_name='Response.ScoreEntry.key', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='value', full_name='Response.ScoreEntry.value', index=1,
            number=2, type=11, cpp_type=10, label=1,
            has_default_value=False, default_value=None,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=_b('8\001'),
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=269,
    serialized_end=325,
)

_RESPONSE = _descriptor.Descriptor(
    name='Response',
    full_name='Response',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='msg', full_name='Response.msg', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='score', full_name='Response.score', index=1,
            number=2, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[_RESPONSE_SCOREENTRY, ],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=207,
    serialized_end=325,
)

_TASKSCORE_TASKSCOREENTRY.fields_by_name['value'].message_type = _LISTVALUE
_TASKSCORE_TASKSCOREENTRY.containing_type = _TASKSCORE
_TASKSCORE.fields_by_name['task_score'].message_type = _TASKSCORE_TASKSCOREENTRY
_RESPONSE_SCOREENTRY.fields_by_name['value'].message_type = _TASKSCORE
_RESPONSE_SCOREENTRY.containing_type = _RESPONSE
_RESPONSE.fields_by_name['score'].message_type = _RESPONSE_SCOREENTRY
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['ListValue'] = _LISTVALUE
DESCRIPTOR.message_types_by_name['TaskScore'] = _TASKSCORE
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
    'DESCRIPTOR': _REQUEST,
    '__module__': 'message_pb2'
    # @@protoc_insertion_point(class_scope:Request)
})
_sym_db.RegisterMessage(Request)

ListValue = _reflection.GeneratedProtocolMessageType('ListValue', (_message.Message,), {
    'DESCRIPTOR': _LISTVALUE,
    '__module__': 'message_pb2'
    # @@protoc_insertion_point(class_scope:ListValue)
})
_sym_db.RegisterMessage(ListValue)

TaskScore = _reflection.GeneratedProtocolMessageType('TaskScore', (_message.Message,), {

    'TaskScoreEntry': _reflection.GeneratedProtocolMessageType('TaskScoreEntry', (_message.Message,), {
        'DESCRIPTOR': _TASKSCORE_TASKSCOREENTRY,
        '__module__': 'message_pb2'
        # @@protoc_insertion_point(class_scope:TaskScore.TaskScoreEntry)
    })
    ,
    'DESCRIPTOR': _TASKSCORE,
    '__module__': 'message_pb2'
    # @@protoc_insertion_point(class_scope:TaskScore)
})
_sym_db.RegisterMessage(TaskScore)
_sym_db.RegisterMessage(TaskScore.TaskScoreEntry)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {

    'ScoreEntry': _reflection.GeneratedProtocolMessageType('ScoreEntry', (_message.Message,), {
        'DESCRIPTOR': _RESPONSE_SCOREENTRY,
        '__module__': 'message_pb2'
        # @@protoc_insertion_point(class_scope:Response.ScoreEntry)
    })
    ,
    'DESCRIPTOR': _RESPONSE,
    '__module__': 'message_pb2'
    # @@protoc_insertion_point(class_scope:Response)
})
_sym_db.RegisterMessage(Response)
_sym_db.RegisterMessage(Response.ScoreEntry)

_TASKSCORE_TASKSCOREENTRY._options = None
_RESPONSE_SCOREENTRY._options = None

_MOLEPROPSERVER = _descriptor.ServiceDescriptor(
    name='MolePropServer',
    full_name='MolePropServer',
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    serialized_start=327,
    serialized_end=383,
    methods=[
        _descriptor.MethodDescriptor(
            name='get_mole_prop',
            full_name='MolePropServer.get_mole_prop',
            index=0,
            containing_service=None,
            input_type=_REQUEST,
            output_type=_RESPONSE,
            serialized_options=None,
        ),
    ])
_sym_db.RegisterServiceDescriptor(_MOLEPROPSERVER)

DESCRIPTOR.services_by_name['MolePropServer'] = _MOLEPROPSERVER

# @@protoc_insertion_point(module_scope)
